---

- name: glance_image_create
  tags: openstack_glance
  hosts: localhost
  connection: local
  roles:
    - glance/create

- name: neutron_net_create
  tags: openstack_neutron
  hosts: localhost
  connection: local
  roles:
    - neutron/network/create

- name: nova_instance_create
  tags: openstack_nova
  hosts: localhost
  connection: local
  roles:
    - nova/instance/create
