---

- name: Create network
  os_network:
    cloud: "{{ cloud }}"
    name: "{{ private_network_name }}"
    state: present

- name: Create subnet
  os_subnet:
    cloud: "{{ cloud }}"
    name: "{{ subnet_name }}"
    allocation_pool_start: "{{ private_allocation_pool_start }}"
    allocation_pool_end: "{{ private_allocation_pool_end }}"
    cidr: "{{ cidr }}"
    dns_nameservers: "{{ dns_nameservers }}"
    enable_dhcp: True
    network_name: "{{ private_network_name }}"
    state: present
