---

- name: Create instance
  os_server:
    cloud: "{{ cloud }}"
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    flavor: "{{ instance_flavor }}"
    timeout: 200
    network: "{{ private_network_name }}"
    auto_ip: 'no'
    state: present
  with_items:
     - { name: "{{ stopped_instance_name }}", image: "{{ image_name }}" }

- name: Stop instance
  os_server_actions:
       cloud: "{{ cloud }}"
       action: stop
       server: "{{ stopped_instance_name }}"
       timeout: 200