---

- name: Create instance
  os_server:
    cloud: "{{ cloud }}"
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    flavor: "{{ instance_flavor }}"
    security_groups: "{{ security_group_name }}"
    timeout: 200
    network: "{{ private_network_name }}"
    auto_ip: 'no'
    state: present
  with_items:
     - { name: "{{ floating_instance_name }}", image: "{{ image_name }}" }

- name: Assign floating ip
  os_floating_ip:
    cloud: "{{ cloud }}"
    network: "{{ external_network }}"
    server: "{{ floating_instance_name }}"
