---

- name: External network crate
  tags: openstack_neutron
  hosts: localhost
  connection: local
  roles:
    - neutron/external_network/create
  vars_files:
    - /home/ahirshbe/git/ansible/variables/main.yml

- name: Private network create
  tags: openstack_neutron
  hosts: localhost
  connection: local
  roles:
    - neutron/network/create
  vars_files:
   - /home/ahirshbe/git/ansible/variables/main.yml

- name: Router create
  tags: openstack_neutron
  hosts: localhost
  connection: local
  roles:
    - neutron/router/create
  vars_files:
    - /home/ahirshbe/git/ansible/variables/main.yml

- name: Image_create
  tags: openstack_glance
  hosts: localhost
  connection: local
  roles:
    - glance/cirros/create
  vars_files:
    - /home/ahirshbe/git/ansible/variables/main.yml

- name: Instance in shutdown state
  tags: openstack_nova
  hosts: localhost
  connection: local
  roles:
    - nova/instance_shutdown_state/create
  vars_files:
    - /home/ahirshbe/git/ansible/variables/main.yml
